# Generated by Django 5.2.8 on 2025-12-08 23:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='VetRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livestockId', models.CharField(blank=True, max_length=100)),
                ('treatment', models.CharField(max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('veterinarian', models.CharField(max_length=150)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('livestock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farm.livestock')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.farmuser')),
            ],
        ),
    ]
